Add Support for Firefox (#15), Fix PluginOptions not working
TBM13/BrowserSearch pull request #20
Opened 2024-05-30 08:11 UTC by ReylordDev

Hey there, thank you for this great plugin!

Closes #7 

I saw that there was no public progress on the Firefox support so I added it myself.
Some information:
- Firefox profiles are just directory names with the format `{stringId}.{profileName}`.
- The Firefox history is in the `places.sqlite` database. There is a _frecency_ value stored for every history entry which I use for calculating the extra score.

This PR also includes two additional changes:
1. I noticed the plugin additional options were not working at all. Changing them in PowerToys had no effect. I added a fix for this by looking at how a different plugin does it.
2. I added a simple installation script to build the project and add it to PowerToys

2024-06-10 02:48 UTC, TBM13 commented
Thanks for the contribution.

About the issue with the plugin options, they are working fine for me. I believe I'm handling them the same way Microsoft does on their plugins. Was there any info on the logs?

2024-06-10 02:56 UTC, TBM13 commented
I believe https://github.com/TBM13/BrowserSearch/pull/20/commits/6962b9ea2417b3ce65fe073261378d8c4842bed3 will reintroduce issues like #5 (fixed with https://github.com/TBM13/BrowserSearch/commit/4adce52aa390ac389ab1e10751e8c0d8a96eb493) since the null-conditional operators were removed. Sometimes Powertoys gives null values for some reason, and when that happens the plugin uses the default values as fallback.

2024-06-10 08:34 UTC, ReylordDev commented
I haven't been able to reproduce the original issue with the plugin settings so I will revert 6962b9e.

2024-06-24 22:23 UTC, tilsgee requested changes
when i try to install it using install.bat, it throws this error:

C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'.
    C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'.
    C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'.
    
and this is problem, because:
1. dotnet SDK for version 8, **ONLY** version 8.0.6 are download able. not 8.0.5
2. for ppl who install newer version of dotnet SDK (for instance, me, who install dotnet SDK 9.0.0 Preview 5), they can't install it

2024-06-24 22:36 UTC, TBM13 commented
> when i try to install it using install.bat, it throws this error:
> 
> C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.NETCore.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'. C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.WindowsDesktop.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'. C:\Tils-Gee\GithubCloned\BrowserSearch\BrowserSearch\BrowserSearch.csproj : error NU1100: Unable to resolve 'Microsoft.AspNetCore.App.Ref (= 8.0.5)' for 'net8.0-windows7.0'.
> 
> and this is problem, because:
> 
> 1. dotnet SDK for version 8, **ONLY** version 8.0.6 are download able. not 8.0.5
> 2. for ppl who install newer version of dotnet SDK (for instance, me, who install dotnet SDK 9.0.0 Preview 5), they can't install it

I haven't tried the install script yet (which should probably be renamed to build.bat) but if you are just looking to install the plugin, follow the instructions in the README.
As for the .NET version, I'm using the one PowerToys uses. As seen [here](https://github.com/TBM13/BrowserSearch/blob/7a84164ca4840c00e66b2f9ecb0f7a98f40f7e40/BrowserSearch/BrowserSearch.csproj#L4), only .NET 8 is selected. I guess VS tries to use the latest point release it can.

2024-06-24 22:37 UTC, TBM13 commented
Btw sorry for the delay @ReylordDev. Code looks good but I haven't been able to test this yet due to university exams. Hopefully I'll review this soon

2024-06-25 08:06 UTC, ReylordDev commented
No rush @TBM13, exams take priority! Also feel free to change the build script as much as you want, I just found it helpful during development.

2024-07-10 02:59 UTC, merged